import type { CookbookSettings } from "./index";

/**
 * Keyword lists are matched whole-word (see ingredients/categorize.ts), so
 * compound names such as "blueberries" need their own entry — a bare "berry"
 * no longer matches inside a longer word.
 */
export const DEFAULT_SETTINGS: CookbookSettings = {
	propsToShow: ["title"],
	shoppingListFilePath: undefined,
	coverProp: "cover",
	recipesFolder: ".",
	recipesTag: "#recipe",
	cookSoonProp: "cook-soon",
	ignorePaths: [],
	hideCheckedItems: false,
	ingredientGroups: [
		{ name: "Dairy",          keywords: ["milk", "butter", "cream", "cheese", "yogurt", "parmesan", "mozzarella", "cheddar", "brie", "feta", "ricotta", "ghee", "creme fraiche", "sour cream", "mascarpone", "whipping cream", "double cream", "single cream", "half and half", "cream cheese"] },
		{ name: "Meat & Poultry", keywords: ["chicken", "beef", "pork", "lamb", "turkey", "bacon", "sausage", "mince", "steak", "duck", "veal", "ham", "pancetta", "chorizo", "salami", "pepperoni", "brisket", "venison", "lard"] },
		{ name: "Fish & Seafood", keywords: ["salmon", "tuna", "cod", "shrimp", "prawn", "fish", "anchovy", "sardine", "crab", "lobster", "scallop", "squid", "halibut", "tilapia", "sea bass", "haddock", "mackerel", "trout", "clam", "mussel", "oyster"] },
		{ name: "Eggs",           keywords: ["egg", "eggs"] },
		{ name: "Nuts",           keywords: ["almond", "walnut", "pecan", "pine nut", "cashew", "peanut", "pistachio", "hazelnut", "macadamia", "nut butter", "peanut butter"] },
		{ name: "Gluten",         keywords: ["flour", "wheat", "bread", "pasta", "noodle", "barley", "rye", "couscous", "breadcrumb", "panko", "semolina", "spelt", "bulgur"] },
	],
	shoppingCategories: [
		{
			name: "Produce",
			keywords: [
				"carrot",
				"onion",
				"garlic",
				"tomato",
				"lettuce",
				"spinach",
				"potato",
				"pepper",
				"cucumber",
				"celery",
				"mushroom",
				"broccoli",
				"cauliflower",
				"cabbage",
				"leek",
				"herb",
				"basil",
				"parsley",
				"cilantro",
				"thyme",
				"rosemary",
				"sage",
				"mint",
				"chive",
				"lemon",
				"lime",
				"apple",
				"banana",
				"berry",
				"berries",
				"blueberry",
				"blueberries",
				"raspberry",
				"raspberries",
				"blackberry",
				"blackberries",
				"cranberry",
				"cranberries",
				"orange",
				"zucchini",
				"courgette",
				"squash",
				"avocado",
				"mango",
				"peach",
				"pear",
				"grape",
				"strawberry",
				"asparagus",
				"corn",
				"sweetcorn",
				"pea",
				"green bean",
				"beetroot",
				"beet",
				"ginger",
				"scallion",
				"spring onion",
				"kale",
				"arugula",
				"rocket",
				"fennel",
				"shallot",
				"radish",
				"artichoke",
				"eggplant",
				"aubergine",
				"sweet potato",
				"bok choy",
				"watercress",
				"endive",
			],
		},
		{
			name: "Dairy & Eggs",
			keywords: [
				"milk",
				"cheese",
				"butter",
				"cream",
				"yogurt",
				"egg",
				"cheddar",
				"mozzarella",
				"parmesan",
				"brie",
				"sour cream",
				"crème fraîche",
				"cream cheese",
				"ricotta",
				"feta",
				"gouda",
				"goat cheese",
				"half and half",
				"ghee",
				"whipping cream",
				"double cream",
				"single cream",
				"mascarpone",
				"cottage cheese",
				"pecorino",
				"gruyere",
				"gruyère",
				"halloumi",
				"provolone",
			],
		},
		{
			name: "Meat & Fish",
			keywords: [
				"chicken",
				"beef",
				"pork",
				"lamb",
				"turkey",
				"bacon",
				"sausage",
				"mince",
				"steak",
				"salmon",
				"tuna",
				"cod",
				"shrimp",
				"prawn",
				"fish",
				"duck",
				"veal",
				"ham",
				"pancetta",
				"anchovy",
				"sardine",
				"crab",
				"lobster",
				"scallop",
				"squid",
				"venison",
				"chorizo",
				"salami",
				"pepperoni",
				"brisket",
				"ribs",
				"fillet",
				"halibut",
				"tilapia",
				"sea bass",
				"haddock",
				"mackerel",
				"trout",
			],
		},
		{
			name: "Pantry",
			keywords: [
				"flour",
				"sugar",
				"salt",
				"oil",
				"vinegar",
				"sauce",
				"pasta",
				"rice",
				"stock",
				"broth",
				"tin",
				"can",
				"spice",
				"cumin",
				"paprika",
				"turmeric",
				"cinnamon",
				"honey",
				"soy sauce",
				"olive oil",
				"lentil",
				"chickpea",
				"black bean",
				"kidney bean",
				"oat",
				"noodle",
				"cornstarch",
				"cornflour",
				"baking powder",
				"baking soda",
				"bicarbonate",
				"yeast",
				"cocoa",
				"chocolate",
				"jam",
				"mustard",
				"ketchup",
				"mayo",
				"mayonnaise",
				"tahini",
				"miso",
				"wine",
				"beer",
				"chili",
				"chilli",
				"curry",
				"bay leaf",
				"breadcrumb",
				"panko",
				"tomato paste",
				"coconut milk",
				"vegetable oil",
				"sesame oil",
				"fish sauce",
				"worcestershire",
				"hot sauce",
				"maple syrup",
				"peanut butter",
				"almond",
				"walnut",
				"pecan",
				"pine nut",
				"cashew",
				"raisin",
				"dried fruit",
				"quinoa",
				"couscous",
				"barley",
				"rotini",
				"penne",
				"fusilli",
				"rigatoni",
				"spaghetti",
				"macaroni",
				"orzo",
				"linguine",
				"farfalle",
				"gnocchi",
				"jasmine rice",
				"basmati rice",
				"oregano",
				"basil",
				"dill",
				"nutmeg",
				"coriander",
				"cardamom",
				"hoisin",
				"sriracha",
				"vanilla",
				"cornflake",
				"crouton",
			],
		},
		{
			name: "Frozen",
			keywords: [
				"frozen",
				"ice cream",
				"sorbet",
				"gelato",
				"frozen peas",
				"frozen corn",
				"frozen spinach",
				"frozen berries",
				"frozen fish",
				"frozen chicken",
				"edamame",
				"frozen pastry",
				"puff pastry",
				"shortcrust pastry",
				"frozen chips",
				"french fries",
			],
		},
		{
			name: "Bakery",
			keywords: [
				"bread",
				"loaf",
				"baguette",
				"croissant",
				"roll",
				"bun",
				"sourdough",
				"brioche",
				"ciabatta",
				"focaccia",
				"bagel",
				"muffin",
				"scone",
				"tortilla",
				"wrap",
				"pitta",
				"pita",
				"naan",
				"flatbread",
				"crumpet",
				"english muffin",
				"pretzel",
				"cracker",
				"breadstick",
			],
		},
	],
};
